# Generated by Django 3.2.8 on 2021-11-02 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_number', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.CharField(max_length=100)),
                ('well_number', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('spud_date', models.DateField()),
                ('survey', models.CharField(max_length=100)),
                ('total_depth', models.IntegerField()),
                ('permit_number', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('kelley_bushing', models.CharField(max_length=100)),
                ('derrick_floor', models.CharField(max_length=100)),
                ('initial_formation', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=100)),
                ('ground_level', models.IntegerField()),
                ('plat_image', models.ImageField(blank=True, default=None, null=True, upload_to='media/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_depth', models.IntegerField()),
                ('ending_depth', models.IntegerField()),
                ('sacks_pumped', models.IntegerField()),
                ('cement_type', models.CharField(max_length=100)),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
        ),
        migrations.CreateModel(
            name='Perforation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_depth', models.IntegerField()),
                ('ending_depth', models.IntegerField()),
                ('perforation_interval', models.CharField(max_length=100)),
                ('perforation_total_holes', models.CharField(max_length=100)),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_depth', models.IntegerField()),
                ('ending_depth', models.IntegerField()),
                ('hole_size', models.CharField(max_length=100)),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
        ),
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_depth', models.IntegerField()),
                ('ending_depth', models.IntegerField()),
                ('sacks_pumped', models.IntegerField()),
                ('cement_type', models.CharField(max_length=100)),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
        ),
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_depth', models.IntegerField()),
                ('ending_depth', models.IntegerField()),
                ('casing_weight', models.CharField(max_length=100)),
                ('casing_grading', models.CharField(max_length=100)),
                ('gauge', models.CharField(choices=[('lrg', '13 3/8"'), ('med', '9 5/8"'), ('sml', '5 1/2"')], default='lrg', max_length=3)),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
        ),
    ]
