# Generated by Django 3.2.8 on 2021-11-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_auto_20211102_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='casing_grading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casing',
            name='casing_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cement',
            name='cement_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cement',
            name='sacks_pumped',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hole',
            name='hole_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perforation',
            name='perforation_interval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perforation',
            name='perforation_total_holes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plug',
            name='cement_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plug',
            name='sacks_pumped',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
