# Generated by Django 3.2.9 on 2021-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_auto_20211104_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='gauge',
            field=models.CharField(choices=[('xlg', '13 3/8"'), ('lrg', '9 5/8"'), ('med', '8 5/8"'), ('reg', '7"'), ('sml', '5 1/2"'), ('xsm', '4 1/2"')], default='lrg', max_length=3),
        ),
    ]
