# Generated by Django 3.2.9 on 2021-11-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_alter_casing_gauge'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='plug_type',
            field=models.CharField(choices=[('DV', 'Diverter Valve'), ('CP', 'Cement Plug'), ('MP', 'Mechanical Plug')], default='CP', max_length=2),
        ),
    ]
